feat(vmd.logger): add warning level to core logging framework
VMDDTE/applications-common-logging pull request #9
Opened 2021-04-15 15:38 UTC by kieronlanning

Add warning level to enable clients to meaningfully representing warning-level log messages.

2021-04-15 15:59 UTC, cedricbrasey submitted a review, later dismissed

2021-04-16 09:02 UTC, mogusbi-motech requested changes
I can't see any changes to `package.json` so could you undo the changes to the `package-lock.json` file please. This was probably because you ran `npm i` instead of `npm ci`.

Package locks should be frozen unless changes to dependencies have been made.

2021-04-16 09:34 UTC, kieronlanning commented
@mogusbi-motech Updated.

2021-04-16 09:35 UTC, nroper commented on src/logging/__tests__/vmd-logger.test.ts
> +  it('should create an warn log when logRequestWarn is called', () => {
Should this be "... a warn log..." instead of "... an warn log..." ?

2021-04-16 09:36 UTC, richmilton submitted a review, later dismissed
LGTM

2021-04-16 09:37 UTC, kieronlanning commented on src/logging/__tests__/vmd-logger.test.ts
> +  it('should create an warn log when logRequestWarn is called', () => {
You found my mad copy and paste skills the test above, I see... Up to you if you want that changed in this release or not.

2021-04-16 09:41 UTC, kieronlanning commented on src/logging/__tests__/vmd-logger.test.ts
> +  it('should create an warn log when logRequestWarn is called', () => {
Resolved.

2021-04-16 09:41 UTC, nroper commented on src/logging/__tests__/vmd-logger.test.ts
> +  it('should create an info warn when logWarn is called', () => {
Also not sure if this is correct: 'info warn'

2021-04-16 09:41 UTC, mogusbi-motech approved these changes
Approved but it would be good to fix those test spec descriptions. We should always aim for the highest standards and this should apply to tests as well.

2021-04-16 09:41 UTC, mogusbi-motech commented on src/logging/__tests__/vmd-logger.test.ts
> +  it('should create an info warn when logWarn is called', () => {
This should be `should create a warn log when logWarn is called`

2021-04-16 09:41 UTC, kieronlanning commented on src/logging/__tests__/vmd-logger.test.ts
> +  it('should create an info warn when logWarn is called', () => {
Updated too.

2021-04-16 09:42 UTC, kieronlanning commented on src/logging/__tests__/vmd-logger.test.ts
> +  it('should create an info warn when logWarn is called', () => {
Updated. already

2021-04-16 09:42 UTC, nroper commented on src/logging/__tests__/vmd-logger.test.ts
> +  it('should create an warn log when logRequestWarn is called', () => {
Guess it wouldn't hurt if you're making other changes re package-lock.json

2021-04-16 09:44 UTC, nroper approved these changes

2021-04-16 09:44 UTC, richmilton approved these changes
LGTM

2021-04-16 11:27 UTC, merged

2021-04-16 11:29 UTC, VMDIT commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- `npm package (@latest dist-tag)`
- [GitHub release](https://github.com/VMDDTE/applications-common-logging/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: